# Generated by Django 4.1.5 on 2023-02-12 17:32

from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField(validators=[groups.validators.validate_start_date])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
